//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patients()
        {
            this.orders = new HashSet<orders>();
        }
    
        public int id { get; set; }
        public string full_name { get; set; }
        public string login { get; set; }
        public string pwd { get; set; }
        public string guid { get; set; }
        public string email { get; set; }
        public int social_sec_number { get; set; }
        public string ein { get; set; }
        public int social_type { get; set; }
        public string phone { get; set; }
        public int passport_s { get; set; }
        public int passport_n { get; set; }
        public System.DateTime birthdate { get; set; }
        public int country { get; set; }
        public int insurance { get; set; }
        public string ipadress { get; set; }
        public string ua { get; set; }
    
        public virtual countries countries { get; set; }
        public virtual insurances insurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
        public virtual social_types social_types { get; set; }
    }
}
