//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_in
    {
        public int id { get; set; }
        public string userLogin { get; set; }
        public string userPassword { get; set; }
        public Nullable<System.DateTime> dateIn { get; set; }
        public string tryIn { get; set; }
    }
}
